
name: employee-manager-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip=24.0
  - pip:
    - django==5.1.6
    - djangorestframework==3.15.0
    - djangorestframework-simplejwt==5.3.1
    - django-cors-headers==4.3.1
    - asgiref==3.8.1
    - PyJWT==2.9.0
